services:
  nuxt:
    build:
      context: .
    container_name: breizhsport-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true  